### ISSUE TITLE
Decompression Errors

### ISSUE THREAD

**Issue by clee-ai** [laz-rs/laz-rs-c#5]
On a couple different files, including https://github.com/PDAL/data/blob/a3d2a351ca1002c7ea4daa96b5c5fcb0fafeaa6f/autzen/autzen-classified.copc.laz, I'm getting `decompression failed` running `cpp_decompressor`. I can't seem to find the issue, any ideas?

**Comment by tmontaigu** [comment]
I cannot test right now, but I know `minilas` has poor support for LAS 1.4 files, try to make sure that you seek to the `offset_to_point_data` before creating the decompressor.
